# Generated by Django 3.1.5 on 2021-02-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('publication_date', models.CharField(max_length=25)),
                ('book_genres', models.CharField(max_length=100)),
                ('plot_summary', models.CharField(max_length=1000)),
            ],
        ),
    ]
