# Generated by Django 3.1.5 on 2021-02-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_genres',
        ),
        migrations.AlterField(
            model_name='book',
            name='plot_summary',
            field=models.TextField(),
        ),
    ]
